/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FilmRentalHistoryResponse {
  filmId?: number;
  id?: number;
  rentalDate?: string;
  rentalPrice?: number;
  returnDate?: string;
  returned?: boolean;
  returnedApproved?: boolean;
  userId?: string;
}
