/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FilmResponse {
  archive?: boolean;
  createdAt?: string;
  director?: string;
  filmPoster?: string;
  genre?: 'ACTION' | 'COMEDY' | 'DRAMA' | 'HORROR' | 'SCI_FI' | 'DOCUMENTARY' | 'ANIMATION';
  id?: number;
  imdbId?: string;
  lastModifiedAt?: string;
  rating?: number;
  synopsis?: string;
  title?: string;
  year?: string;
}
