/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FilmFeedbackResponse } from '../models/film-feedback-response';
export interface PageResponseFilmFeedbackResponse {
  content?: Array<FilmFeedbackResponse>;
  first?: boolean;
  last?: boolean;
  pageNumber?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
