/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RentedFilmResponse {
  director?: string;
  filmTitle?: string;
  id?: number;
  imdbId?: string;
  rentalDate?: string;
  rentalPrice?: number;
  returnApproved?: boolean;
  returned?: boolean;
}
