/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FilmResponse } from '../../models/film-response';

export interface GetFilmById$Params {
  id: number;
}

export function getFilmById(http: HttpClient, rootUrl: string, params: GetFilmById$Params, context?: HttpContext): Observable<StrictHttpResponse<FilmResponse>> {
  const rb = new RequestBuilder(rootUrl, getFilmById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FilmResponse>;
    })
  );
}

getFilmById.PATH = '/films/{id}';
