/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FilmRequest } from '../../models/film-request';
import { FilmResponse } from '../../models/film-response';

export interface UpdateFilm$Params {
  id: number;
      body: FilmRequest
}

export function updateFilm(http: HttpClient, rootUrl: string, params: UpdateFilm$Params, context?: HttpContext): Observable<StrictHttpResponse<FilmResponse>> {
  const rb = new RequestBuilder(rootUrl, updateFilm.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FilmResponse>;
    })
  );
}

updateFilm.PATH = '/films/{id}';
