spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/film_social_network
    username: luca
    password: luca
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: abf7a0936393bf1f6143137367ccbdf3985d6379ce772634f5eff2131880604b
      expiration: 86400000

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      poster-cover-path: ./uploads
  server:
    port: 8088

logging:
  level:
    org:
      springframework: INFO
    com:
      luca: DEBUG

springdoc:
  swagger-ui:
    default-model-expand-depth: 1
    default-model-rendering: model
