/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FilmRentalHistoryResponse } from '../../models/film-rental-history-response';

export interface GetAllRentalHistories$Params {
}

export function getAllRentalHistories(http: HttpClient, rootUrl: string, params?: GetAllRentalHistories$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FilmRentalHistoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllRentalHistories.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FilmRentalHistoryResponse>>;
    })
  );
}

getAllRentalHistories.PATH = '/film-rental-histories';
