/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FilmRentalHistoryRequest } from '../../models/film-rental-history-request';
import { FilmRentalHistoryResponse } from '../../models/film-rental-history-response';

export interface UpdateRentalHistory$Params {
  id: number;
      body: FilmRentalHistoryRequest
}

export function updateRentalHistory(http: HttpClient, rootUrl: string, params: UpdateRentalHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<FilmRentalHistoryResponse>> {
  const rb = new RequestBuilder(rootUrl, updateRentalHistory.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FilmRentalHistoryResponse>;
    })
  );
}

updateRentalHistory.PATH = '/film-rental-histories/{id}';
